django_urlshortener/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from rest_framework import routers

from urlshortener import views as urlsh_views
from users import views as user_views

router = routers.DefaultRouter()
router.register('profiles', user_views.ProfileView)
router.register('urls', urlsh_views.UrlView)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('', urlsh_views.shortener_page, name='shortener'),
    path('short/', urlsh_views.shortener_post, name='ajax_shortener'),
    path('rest-api/',include(router.urls)),
    re_path('(?P<short_url>[a-zA-Z0-9_-]+)/', urlsh_views.shortener_redirect, name='shortener_redirect' ),
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout_then_login
from . import views as user_views


urlpatterns = [
    path('profile/', user_views.profile, name='profile'),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', logout_then_login, name='logout')
]

urlshortener/models.py
from django.db import models
from django.contrib.auth.models import User


class Url(models.Model):
    short_url = models.SlugField(max_length=200, unique=True)
    url = models.URLField(max_length=200)
    date_submited = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return self.url

users/models.py
from django.db import models
from django.db.models.signals import post_save
from urlshortener.models import Url
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    urls = models.ManyToManyField(Url)

    def __str__(self):
        return self.user.username


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


post_save.connect(create_user_profile, sender=User)

urlshortener/forms.py
from django import forms
from .models import Url


class UrlshortenerForm(forms.ModelForm):
    url = forms.URLField()

    class Meta:
        model = Url
        fields = ['url']

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

urlshortener/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import redirect
from rest_framework import viewsets

from .serializers import UrlSerializer
from .forms import UrlshortenerForm
from .utils import generate_key
from users.models import Profile
from .models import Url


def shortener_page(request):
    form = UrlshortenerForm()
    return render(request, 'urlshortener/shortener.html', {'form': form, 'shortener_page': 'active'})

def shortener_post(request):
    current_user = request.user

    if request.method == 'POST':
        form = UrlshortenerForm(request.POST)

        if form.is_valid():
            obj = Url.objects.filter(url=request.POST['url'])

            if obj.exists():
                return JsonResponse({'short_url': obj[0].short_url})

            url = form.save(commit=False)
            short_url = url.short_url = generate_key()
            url.save()

            if current_user.is_authenticated:
                profile = Profile.objects.get(user=current_user)
                profile.urls.add(url)

            return JsonResponse({'short_url': short_url})

def shortener_redirect(request, short_url):
    url = Url.objects.get(short_url=short_url)
    return redirect(url)

class UrlView(viewsets.ModelViewSet):
    queryset = Url.objects.all()
    serializer_class = UrlSerializer

users/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from rest_framework import viewsets

from .serializers import ProfileSerializer, UserSerializer
from .forms import UserRegisterForm
from .models import Profile


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()

    else:
        form = UserRegisterForm()
    return render(request, "users/register.html", {'form': form})


@login_required
def profile(request):
    profile = Profile.objects.get(user=request.user)

    context = {
        'profile': profile,
        'profile_page': 'active'
    }

    return render(request, 'users/profile.html', context)

class ProfileView(viewsets.ModelViewSet):
    queryset = Profile.objects.all()
    serializer_class = ProfileSerializer

templates/base.html
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style type="text/css">
        a {
            font-size: 24px;
        }
    </style>

    <title>{% block title %}{% endblock %}</title>
    <title>sdfsd</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#e3f2fd;">
    <a class="navbar-brand" href="{% url 'shortener' %}">
        <img src="https://u-uniq.co.za/wp-content/uploads/2018/10/site-logo-1.png" width="65" height="65">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item {{ profile_page }}">
                    <a class="nav-link" href="{% url 'profile' %}">Home <span class="sr-only">(current)</span></a>
                </li>
            {% endif %}
            <li class="nav-item {{ shortener_page }}">
                <a class="nav-link" href="{% url 'shortener' %}">URLshortener</a>
            </li>
        </ul>
        <span class="navbar-text">
    </span>
    </div>
    <div class="form-inline my-2 my-lg-0">
        {% if not user.is_authenticated %}
            <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
            <a href="{% url 'register' %}" class="btn btn-outline-secondary ml-2">Sign up</a>
        {% else %}
            <a href="{% url 'logout' %}" class="btn btn-outline-secondary">Log Out</a>
        {% endif %}
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/urlshortener/shortener.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Shortener
{% endblock title %}
{% block content %}
    <script type="text/javascript">
        $(function () {
            $("#submitButton").click(function () {
                let form = $('#formId').serialize();
                $.ajax({
                    type: 'POST',
                    url: "{% url 'ajax_shortener' %}",
                    data: form,
                    success: function (data) {
                        if (data) {
                            $("h5").text('http://127.0.0.1:8000/' + data.short_url);
                            $("small").text($('#id_url').val());
                            $('#url-result').attr("href", data.short_url);
                            $('#id_url').val('');
                        }
                    },
                    dataType: 'json'
                });
            });
        });

    </script>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-9">
                <div class="card">
                    <div class="card-body">
                        <h2>Shortener</h2>
                        <form method="POST">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                {{ form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button id="submitButton" class="btn btn-outline-primary" type="button">Shorten</button>
                            </div>
                            <a href="#" id="url-result"
                               class="list-group-item list-group-item-action flex-column align-items-start">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1"></h5>
                                </div>
                                <small class="text-muted"></small>
                            </a>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Log In
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <h2>Log In</h2>
                        <form method="POST">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                {{ form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-outline-primary" type="submit">Log In</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/users/profile.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h2>{{ profile }}</h2>
    <div class="list-group">
        {% for url in profile.urls.all %}
            <a href="{{ url.url }}" class="list-group-item list-group-item-action flex-column align-items-start">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ url.url|slice:"0:60" }}...</h5>
                    <small class="text-muted">{{ url.date_submited }}</small>
                </div>
                <small class="text-muted">http://127.0.0.1:8000/{{ url.short_url }}</small>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Register
{% endblock title %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <h2>Sign Up</h2>
                        <form method="POST">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                {{ form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-outline-primary" type="submit">Sign Up</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}